Resourece:
  MyEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ""
      KeyName: "NVKey"
      InstanceType: "t2.micro"
      Tags:
        - Name: mycfdemo1
        - Env: devops




