Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    Description: Enter t2.micro, t2.small or t2.medium. Default is t2.micro
  ImageName:
    Type: String
    Default: "ami-053b0d53c279acc90"
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 
        Ref: ImageName
      KeyName: "NVKey"
      InstanceType: 
        Ref: InstanceTypeParameter
      Tags:
        - Key: "name"
          Value: "mycfdemo1"
        - Key: "Env"
          Value: "Dev" 
Outputs:
  Instance ID:
    Description: The Instance ID
    Value: !Ref MyEC2Instance
  My EC2Instance Public IP:
    Description: MyEC2Instance Public IP
    Value: !GetAtt MyEC2Instance.PublicIp

  My EC2Instance Private IP:
    Description: MyEC2Instance Private IP
    Value: !GetAtt MyEC2Instance.PrivateIp




