Resources:
  MyEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0f5ee92e2d63afc18"
      KeyName: "NVKey"
      InstanceType: "t2.micro"
      Tags:
        - Key: "name"
          Value: "mycfdemo1"
        - Key: "Env"
          Value: "Dev"




