Resources:
  MyEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-053b0d53c279acc90"
      KeyName: "NVKey"
      InstanceType: "t2.micro"
      Tags:
        - Key: "name"
          Value: "mycfdemo1"
        - Key: "Env"
          Value: "Dev" 




